name: Docker build and push

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  docker-build-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: evvvvan
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: evvvvan/go-chatgpt-api:arm64
          platforms: linux/arm64
